### ISSUE TITLE
Packages refinement - Iter. I

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#110]
## Description

Related issue: #99 

Fix the issues detected during testing.

## Tasks

- [ ] #88
- [x] #89
- [x] #90
- [x] #91
- [ ] #94
- [x] https://github.com/wazuh/wazuh-indexer/issues/101
- [x] https://github.com/wazuh/wazuh-indexer/issues/102
- [x] https://github.com/wazuh/wazuh-indexer/issues/103
- [ ] https://github.com/wazuh/wazuh-indexer/issues/104
- [x] https://github.com/wazuh/wazuh-indexer/issues/105
- [x] https://github.com/wazuh/wazuh-indexer/issues/106
- [x] https://github.com/wazuh/wazuh-indexer/issues/107
- [x] https://github.com/wazuh/wazuh-indexer/issues/108
- [x] https://github.com/wazuh/wazuh-indexer/issues/138
- [ ] https://github.com/wazuh/wazuh-indexer/issues/124

> Current testing iteration of wazuh-indexer@4.9.0 packages concluded with errors.
> We'll work on these issues and open a new testing iteration.
> 

_Originally posted by @AlexRuiz7 in https://github.com/wazuh/wazuh-indexer/issues/99#issuecomment-1881602001_

## Implementation restrictions
- Work only on issues in **backlog**.

**Comment by AlexRuiz7** [comment]
Remaining issues are improvements and will be addressed in the future.
