### ISSUE TITLE
Wazuh packages redesign tier 1 - Stage 2 - Migrate Wazuh indexer

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#155]
## Description

We are on an effort to modernize the packages' generation and lifecycle. This issue aims to track the effort to migrate the packages' generation process from the `wazuh-packages` repository and automate its generation, testing and delivery steps of their lifecycle.

The tasks listed below are extracted from [this internal request](https://github.com/wazuh/internal-devel-requests/issues/712). Use that issue for additional information and requirements.

Note that most of these tasks are already part of the #54 project. We'll use that one for development and this one for tracking, describing the steps taken for each of them.

## Tasks

- [x] Migrate code into target repository for manual package generation
- [x] Automate packages generation through CI
- [x] Automate packages testing through CI
- [x] Add secrets to GH (to upload packages to S3)
- [x] Upload packages to S3 through CI

**Comment by rauldpm** [comment]
First estimated ETA provided by @AlexRuiz7: `2024/03/22`

**Comment by AlexRuiz7** [comment]
Manual and automatic packages generation is already implemented and tested.

Check https://github.com/wazuh/wazuh-indexer/issues/54

The process is documented in https://github.com/wazuh/wazuh-indexer/tree/4.9.0/scripts

**Comment by rauldpm** [comment]
The repository has been configured with CI secrets, please, refer to the main comment of the https://github.com/wazuh/wazuh-jenkins/issues/6290 issue to check the secrets names, the CI used has been configured to put and get objects from the development warehouse
