### ISSUE TITLE
Update mappings for the vulnerability-states index

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#176]
## Description

Replace the field `ecs.version` with `wazuh.schema.version`.

## Tasks

- [ ] Update the fields for the ecs submodule.
- [ ] Test
- [ ] Update events generator for the ecs submodule.
- [ ] Update the index template on wazuh/wazuh repository.
