### ISSUE TITLE
Plugins PoC - Java

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer#234]
## Description

To better understand how plugins work, their lifecylce, how they interact with core functionalities and how to develop them in general, we are going to develop a simple plugin for `wazuh-indexer` that exposes an API to manage ToDos, as a proof of concept. We'll use Java as the programming language. 

As a definition of done, we expect to have an API from which it's possible to:

- **C**reate ToDos
- **R**ead ToDos
- **U**pdate ToDos
- **D**elete ToDos

### ToDo model

The ToDos will be stored using an index, for example: `wazuh-todos`. Each of the documents in the index could have these properties:

- `id`: uuid
- `title`: string
- `description`: text
- `due_date`: date

The index name and its fields must follow the naming convention.

- https://opensearch.org/docs/latest/im-plugin/#naming-restrictions-for-indexes
- https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html#_guidelines_for_field_names

### Tasks

- [x] Create a plugin using the existing template.
- [x] Rename and set up the plugin accordingly.
- [x] Create tests.
- [x] Create routes.
- [x] Create route handles: request, action, response.
- [x] Create ToDo model.
- [ ] Create Index manager.

**Comment by f-galland** [comment]
I was able to index data to an index using a custom REST endpoint by extending the `RestIndexAction` class and supplying it with custom routes and overriding the `prepareRequest()` method with one with hardcoded values:

```java
public class RestHelloWorldAction extends RestIndexAction {

  public static final String HELLO_WORLD_INDEX_NAME = "helloworld";

  @Override
  public String getName() {
    return "rest_handler_hello_world";
  }

  @Override
  public List<Route> routes() {
    return unmodifiableList(asList(
        new Route(POST, "/_plugins/hello_world")));
  }

  @Override
  public RestChannelConsumer prepareRequest(RestRequest request, final NodeClient client) throws IOException {
    assert request.params().get("id") == null : "non-null id: " + request.params().get("id");
    // default to op_type create
    request.params().put("index", HELLO_WORLD_INDEX_NAME );
    request.params().putIfAbsent("op_type", "create");
    return super.prepareRequest(request, client);
  }
}
```

**Comment by f-galland** [comment]
I'm working on this PoC in my own repo:
* https://github.com/f-galland/opensearch-plugin-crud-sample

**Comment by f-galland** [comment]
At present, the plugin can index data, but we have no control over the contents of the data itself. I'm heading my research into trying to validate/sanitize incoming data.

**Comment by f-galland** [comment]
I got tests somewhat working by basing my own classes on:
* https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/rest/action/document/RestIndexActionTests.java

![Image](https://github.com/wazuh/wazuh-indexer/assets/99492720/56f9bcb8-2043-4bcc-872d-2ba00f8d35d7)

Various warnings pop up, and this is still only testing writing to indices, so I need to dig deeper into the reference code above.

**Comment by f-galland** [comment]
It seems that we should use yaml based tests for the rest layer:
* https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer

**Comment by f-galland** [comment]
I managed to get a simple REST API yaml-based test by following:
* https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/README.md

Various examples are present under that folder as well:
* https://github.com/opensearch-project/OpenSearch/tree/main/rest-api-spec/src/main/resources/rest-api-spec/


The following test definition indexes data by hitting the `_plugins/todo` endpoint with a POST request and `{"foo":"bar"}` as its content.
It then takes the `_id` field from the reply and stores it into a `document_id` ["stash" variable](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/README.md#set).
After that, a GET operation on the `/todo` index looks for that document's `id` and checks whether the content is indeed `{"foo":"bar"}`.

```yaml
---
"CRUD test":
    - do:
        _plugins.todo:
            body: { foo: bar }

    - set: { _id: document_id }
    - match: { _index: todo }

    - do:
        get:
            index: todo
            id: $document_id
    - match: { _source: { foo: bar } }
```

However I'm currently stuck at creating a test for a `PUT` method on the same endpoint (which in my current plugin, updates the content of a particular "todo task").
I think the issue might be related to the plugin's API `json` definition file under `src/yamlRestTest/resources/rest-api-spec/api/`, which currently looks like the following:
```json
{
  "_plugins.todo": {
    "stability" : "stable",
    "url": {
      "paths": [
        {
          "path": "/_plugins/todo",
          "methods": [
            "POST",
            "PUT"
          ]
        }
      ]
    },
    "body": {
      "description": "The ToDo plugin's document manipulation endpoint"
    }
  }
}
```

**Comment by f-galland** [comment]
I got the `yaml` REST API tests working.

In order to do so, the API needs to be properly defined in `json` files under `src/yamlRestTest/resources/rest-api-spec/api/`

There needs to be a `json` file per API endpoint and method:

#### _plugins.todo_create.json
```json
{
  "_plugins.todo_create": {
    "stability" : "stable",
    "url": {
      "paths": [
        {
          "path": "/_plugins/todo",
          "methods": [
            "POST"
          ]
        }
      ]
    },
    "body": {
      "description": "The document"
    }
  }
}
```
#### _plugins.todo_read.json
```json
{
  "_plugins.todo_read": {
    "stability" : "stable",
    "url": {
      "paths": [
        {
          "path": "/_plugins/todo/{id}",
          "methods": [
            "GET"
          ],
          "parts": {
            "id":{
              "type":"string",
              "description":"The id of the document to update"
            }
          }
        }
      ]
    }
  }
}
```
#### _plugins.todo_update.json
```json
{
  "_plugins.todo_update": {
    "stability" : "stable",
    "url": {
      "paths": [
        {
          "path": "/_plugins/todo/{id}",
          "methods": [
            "PUT"
          ],
          "parts": {
            "id":{
              "type":"string",
              "description":"The id of the document to update"
            }
          }
        }
      ]
    },
    "body": {
      "description": "The document"
    }
  }
}
```
#### _plugins.todo_delete.json
```json
{
  "_plugins.todo_delete": {
    "stability" : "stable",
    "url": {
      "paths": [
        {
          "path": "/_plugins/todo/{id}",
          "methods": [
            "DELETE"
          ],
          "parts": {
            "id":{
              "type":"string",
              "description":"The id of the document to update"
            }
          }
        }
      ]
    }
  }
}
```

Each of these need to:
* have a parent object key named the same as the file (it doesn't have to match the endpoint name verbatim).
* Declare the path of the endpoint and the methods it can accept
  * Placeholders can be used (as examplified in the `id` fields in the read, update and delete files above) in the path
  * the `parts` object contains a list of path variables.

It's important to detail the usafe of each of these endpoints correctly, since the yaml tests are based on these definitions.

The yaml tests have [their own syntax](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/README.md) and need to be placed under `src/yamlRestTest/resources/rest-api-spec/test/plugin_name`

I've created the following test files (one for accepted API method):

#### 20_create.yml
```json
---
"Create test":
    - do:
        _plugins.todo_create:
            body: { foo: bar }

    - set: { _id: document_id }
    - match: { _index: todo }

    - do:
        get:
            index: todo
            id: $document_id
    - match: { _source: { foo: bar } }

```

#### 30_read.yml
```json
---
"Read test":
    - do:
          index:
              index:  todo
              id:     1000
              body:
                  foo:    bar

    - do:
          _plugins.todo_read:
              id: 1000
    - match: { _index: todo }
    - match: { _source: { foo: bar } }
```

#### 40_update.yml
```json
---
"Update test":
    - do:
          index:
              index:  todo
              id:     1000
              body:
                  foo:    bar

    - do:
        _plugins.todo_update:
           id: 1000
           body: { doc: { foo: baz } }

    - do:
          get:
              index: todo
              id: 1000
    - match: { _source: { foo: baz } }
```

#### 50_delete.yml
```json
---
"Delete test":
    - do:
          index:
              index:  todo
              id:     1000
              body:
                  foo:    bar

    - do:
          _plugins.todo_delete:
              id: 1000
    - match: { _index: todo }
    - match: { result: deleted }

```


The `_plugins.todo_create`, `_plugins.todo_read`, `_plugins.todo_update` and `_plugins.todo_delete` sections actually reference the API spec json from before.
The `20_create.yml` test starts by calling `/_plugins/todo` with a POST (as defined in the appropriate API spec file) and creating which creates a document with an automatically generated `_id`.
The `_id` field is then read from the reply and stored into a variable called `document_id`.

The second `do:` section runs a get query on the `todo` index with the `_id` stored in the `document_id` variable and then checks whether the `_source` field matches what we've stored in the document.

The rest of the tests start with the indexing of a document by means of the built-in `index` API.
After that, we call our custom read, update and delete endpoints on the specified document `_id`. We then cehck if the contents are as expected by means of a `match` 

![Image](https://github.com/wazuh/wazuh-indexer/assets/99492720/af1a69b0-3226-4097-9448-fe24b98def0e)

**Comment by f-galland** [comment]
It was helpful to browse through the built in yaml tests and the rest api spec files under:
* https://github.com/opensearch-project/OpenSearch/tree/main/rest-api-spec/src/main/resources/rest-api-spec

**Comment by f-galland** [comment]
All of the above code can be checked out in the repo I've set up for these tests:
* https://github.com/f-galland/opensearch-plugin-crud-sample/tree/main/src/yamlRestTest/resources/rest-api-spec

I've now moved on to building unit tests for our custom classes.

**Comment by AlexRuiz7** [comment]
### Conclusions

Before closing this issue, we'll be reviewing each of the tasks.

- We have been able to create a plugin using the [OpenSearch plugin template repo](https://github.com/opensearch-project/opensearch-plugin-template-java). We have renamed and configured the plugin is described in the README.
- We created basic unit and integration tests.
- We implemented a REST HTTP API to manage Tasks.
