### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-indexer repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-indexer#275]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-indexer repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] Bump revision for branch 4.9.0 on wazuh-indexer repository.
- [x] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-indexer repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-indexer/releases/tag/v4.9.0-alpha1.
