### ISSUE TITLE
Data model diagrams

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#345]
## Description

The goal of this issue is to generate the data persistence model described in #344. To do that, we'll generate an E/R diagram and iterate it until the data model fulfills the requirements.

## Tasks

- [x] Create a basic Entity-Relation diagram to design the new data persistence model.
- [x] Ensure the design allows RBAC.
- [ ] Iterate the diagram, including the most important fields.

**Comment by AlexRuiz7** [comment]
## Entities

```mermaid
---
title: Wazuh Data Model
---
erDiagram
    AGENT
    COMMAND
    ALERT
    INVENTORY
    VULNERABILITY
    FIM
    SCA
    STATISTICS

```

**Comment by AlexRuiz7** [comment]
Moved to the Feature Complete stage.

**Comment by AlexRuiz7** [comment]
To be revisited in the future.

**Comment by Sc0r** [comment]
Hi, please correct me if I'm mistaken.
1. Was this section originally part of the upcoming wazuh 5.0 release, but has now been excluded?
2. Is this section the part which could have allowed group tags for all indexes, like vulnerability?

We are very interested in a solution which allows multiple tenants to have each their individual vulnerability index, or at least, a label/tag which allows subsequent RBAC by agent group. As we understand, this is the only way to implement multi-tenancy for all indexes on wazuh.

**Comment by Sc0r** [comment]
Hi @AlexRuiz7 

1. Thank you for these details. I assume the feature-split between the upcoming releases explains why some issues like this one got set to 'not planned' despite being technically feature complete.
2. That agent.group approach sounds much more straight-forward and a document level security layer based on this should suffice to build clearly separated tenancies. I'm looking forward to testing this feature for us when it arrives in one of the upcoming releases.
