### ISSUE TITLE
Update index template for the vulnerability state index.

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#382]
## Description

Update the index template to fulfill the requirements of the following issues:

- https://github.com/wazuh/wazuh/issues/25480
- https://github.com/wazuh/wazuh/issues/25482

## Tasks

- [x] Update tooling to generate the index template under the ecs/vulnerability-detector folder
- [x] Update the event generator under the same folder.
- [x] Test the index template
