### ISSUE TITLE
Create new endpoint on the Command Manager plugin

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#412]
## Description

We need to create a new HTTP Rest API to the Command Manager plugin, exposing a POST endpoint that receives the command action request from the Management API on the Wazuh Server node, or from the Content Manager plugin (this is yet to be defined). Independently of the source, the Command Manager endpoint must receive this information, fit it into the Command index data model and persist the data on the index.

The endpoint must define the endpoint and its parameters, validate the data and persist it as the Commands index data model requires.

Be aware of any security concerns. On a next iteration, we want to secure the endpoint, so only allowed clients are allowed to use the endpoint.

## Tasks

- [ ] Implement the ActionPlugin interface
- [ ] Implement the Rest endpoint (resthandler, model, ...)
- [ ] Validate the data
- [ ] Persist the data into the commands index.

**Comment by f-galland** [comment]
Superseded by https://github.com/wazuh/wazuh-indexer-plugins/issues/69
