### ISSUE TITLE
Data Persistence Model Redesign MVP validation test - I

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#478]
## Description

For the delivery of the MVP phase of https://github.com/wazuh/wazuh/issues/22887, we need to check that:

- [x] The packages can be built.
- [x] The packages can be installed.
- [x] The Wazuh Indexer service starts and runs (start, stop, restart).
- [x] A Wazuh Indexer cluster can be formed.
- [x] Wazuh Indexer plugins are installed (listed by the API).
- [x] The setup plugin
  - [x] index templates and indices are created (listed by the API).
  - [x] Every index template includes agent related fields (`agent.id` and `agent.groups`).
  - [x] Every index template's index pattern allows a suffix (ends with `*`).
- [x] The Command Manager 
  - [x] API listens to POST HTTP request
  - [x] index template is created
  - [x] indexes data on the `.commands` index on a successful HTTP POST request
  - [x] sends data to the Management API
- [x] Wazuh Indexer can be uninstalled. 

## Tasks

For each of the sections, provide instructions and evidences of their testing.

**Comment by QU3B1M** [comment]
### Validation process

1. The packages can be built.
    Check the packages are built as result of the GHA `Build` workflow
    ```bash
    #!/bin/bash
    
    url=$1
    
    if curl --output /dev/null --silent --head --fail "$url"; then
      echo "Wazuh indexer package was built."
    else
      echo "Error: Wazuh indexer not found."
    fi
    ```
    <details><summary>Real execution</summary>

      ```shellsession
      bash ./check_build.sh https://github.com/wazuh/wazuh-indexer/actions/runs/11406244332/artifacts/2074853568
      Wazuh indexer package was built.
      ```
2.

**Comment by QU3B1M** [comment]
Created issue to track the detected bug:
- https://github.com/wazuh/wazuh-indexer/issues/481

**Comment by AlexRuiz7** [comment]
Added a couple of tests more.

**Comment by QU3B1M** [comment]
Added new validations to `06_check_setup_plugin.sh` script, the comment https://github.com/wazuh/wazuh-indexer/issues/478#issuecomment-2422805448 was updated with the new script execution.

**Comment by QU3B1M** [comment]
The scripts were executed on the package generated with the fix checking the index-pattern is fixed and working

```powershell
bash ./06_check_setup_plugin.sh 192.168.56.10

Fetching templates from Wazuh indexer cluster...
Validating templates...
  Template index-template-agent is created correctly.
  Error: Template index-template-alerts is missing required field 'agent.groups'.
  Template index-template-fim is created correctly.
  Template index-template-packages is created correctly.
  Template index-template-processes is created correctly.
  Template index-template-system is created correctly.
  Error: Template index-template-vulnerabilities is missing required field 'agent.groups'.
Some templates were not created correctly:
  index-template-alerts
  index-template-vulnerabilities

Fetching indices from Wazuh indexer cluster...
Fetching protected indices from Wazuh indexer cluster...
Validating index patterns...
  Index pattern wazuh-alerts-5.x-* is valid.
  Index pattern wazuh-states-vulnerabilities* is valid.
  Index pattern wazuh-states-inventory-system* is valid.
  Index pattern wazuh-states-inventory-packages* is valid.
  Index pattern .agents* is valid.
  Index pattern wazuh-states-fim* is valid.
  Index pattern wazuh-states-inventory-processes* is valid.
Index-patterns validated successfully.
```

**Comment by QU3B1M** [comment]
The **Setup plugin validations** executed on the package with the fix **passed successfully** 
```powershell
bash 06.sh 192.168.68.5
Fetching templates from Wazuh indexer cluster...
Validating templates...
  Template index-template-agent is created correctly.
  Template index-template-alerts is created correctly.
  Template index-template-fim is created correctly.
  Template index-template-packages is created correctly.
  Template index-template-processes is created correctly.
  Template index-template-system is created correctly.
  Template index-template-vulnerabilities is created correctly.
All templates are correctly created.

Fetching indices from Wazuh indexer cluster...
Fetching protected indices from Wazuh indexer cluster...
Validating index patterns...
  Index pattern wazuh-alerts-5.x-* is valid.
  Index pattern wazuh-states-vulnerabilities* is valid.
  Index pattern wazuh-states-inventory-system* is valid.
  Index pattern wazuh-states-inventory-packages* is valid.
  Index pattern .agents* is valid.
  Index pattern wazuh-states-fim* is valid.
  Index pattern wazuh-states-inventory-processes* is valid.
Index-patterns validated successfully.
```
