### ISSUE TITLE
MVP Indexer refinement (I)

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-indexer#496]
# Description

We want to iterate and polish the MVP indexer so we can test the overall design of the solution.

Currently, we have identified the following improvements:

- [x]  https://github.com/wazuh/wazuh-indexer/issues/491 
- [x] https://github.com/wazuh/wazuh-indexer/issues/499
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/122
- [x] #525 
- [x] #539 
- [x] #518 
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/147
- [x] Review index templates, documentation and events generators are synced

**Comment by AlexRuiz7** [comment]
> [Under analysis] The default opensearch.yml file contains node-1 as default node name, and the certificates are named indexer. I believe we should use the same name: node-1. So we prepare this better for a cluster environment.

Won't do. We might revisit this later in the future.
