### ISSUE TITLE
New vulnerabilities index

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-indexer#5]
## Introduction

With the new vulnerability detector work (https://github.com/wazuh/wazuh/issues/14153), we are going to create new indices which will contain the information about all active vulnerabilities in all endpoints across a Wazuh environment.

## Design

- The index won't have a timestamp, as it will represent the current global status of all vulnerabilities found in all endpoints
- The index will contain only [ECS](https://www.elastic.co/guide/en/ecs/current/index.html) fields, and will reject any non-mapped fields with an error
- The index will have the necessary settings to ensure the [new dashboard](https://github.com/wazuh/wazuh-kibana-app/issues/5763) can work without any performance errors

We also need to investigate a way for our indexer package to deploy the indexes and their mappings on a fresh installation, and upgrade them on upgrades.

To test the performance, we will use a canonical environment as described in our documentation.

## Plan

- [x] #6
- [x] Create a sample dataset for testing
- [x] #31 
- [x] Define default search fields
- [x] Create the installation/update procedure

## Related issues

We will include here related issues outside our plan which might be affected by this development.

**Comment by AlexRuiz7** [comment]
**Task**: Create a sample dataset for testing

Done in https://github.com/wazuh/wazuh-indexer/issues/6#issuecomment-1717919242

**Comment by AlexRuiz7** [comment]
### Define default search fields

We are using these [ECS fields](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html) in the index:

- ecs
- base
- event
- agent
- package
- operating system
- vulnerability

I suggest adding at least one property of each field to the default search fields of the index. We need to have in consideration the significance of these properties, as well as their type, as they can have impact on the searched performed afterwards. For example:

> A keyword field type contains a string that is not analyzed. It allows only exact, case-sensitive matches.
Source: [OpenSearch's Keyword field type documentation](https://opensearch.org/docs/latest/field-types/supported-field-types/keyword/)

These could be:

| Field | Type  |
| --- | --- |
| base.tags | keyword[] |
| agent.id | keyword |
| ecs.version | keyword |
| event.id | keyword |
| event.module | keyword |
| event.severity | long |
| WIP | WIP |



Resources:

- https://codecurated.com/blog/basics-of-elasticsearch-for-developer/
- https://codecurated.com/blog/elasticsearch-text-vs-keyword/

**Comment by AlexRuiz7** [comment]
### Create the installation/update procedure

@wazuh/security-warriors will be in charge of this.

**Comment by AlexRuiz7** [comment]
I re-open the issue because I found a problem with the mappings. The properties of the `host.os` field have no mappings and are shown as `unknown`.

![image](https://github.com/wazuh/wazuh-indexer/assets/15186973/23d4b097-9d77-400e-857f-e6b3db31aaa4)


But the index template actually has the mappings for that field.

![image](https://github.com/wazuh/wazuh-indexer/assets/15186973/a5811c1e-492a-4154-a9a9-071db8c32cb5)


I've been investigating, and I think it is caused by the processor `add_host_metadata` which is missing in OpenSearch, but seems to be the required processor for this field.

![image](https://github.com/wazuh/wazuh-indexer/assets/15186973/6a6e2652-1825-4663-a6bf-1dc95311ad25)

Looking at that table, looks like the `user_agent` processor can be used as well, but this requires the `os` field to be nested under the `user_agent` field instead of `host`. This processor is present in OpenSearch.

Resources:

- https://doc.wikimedia.org/ecs/
- https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/user-agent/
