### ISSUE TITLE
Phase II: Assembly - Automate the generation of final packages

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#76]
## Description

Building packages for `wazuh-indexer` takes 2 steps: 
  
- Build: compiles and packages the `wazuh-indexer` project.
- Assembly: installs plugins and adds configuration files for production.

This issue focuses on the **Assembly** phase, following the requirements defined in its parent [issue](#54).

We need to generate final packages for:

- [x] `linux-arm64.tar.gz`
- [x] `linux-x64.tar.gz`
- [ ] `aarch64.rpm` (ARM runners needed)
- [x] `x86_64.rpm`
- [x] `amd64.deb`
- [ ] `arm64.deb` (ARM runners needed)

For each of them, these tasks are needed:

- Download min package
- Decompress
- Install plugins
- Install configuration files
- Compress

## Tasks

- [x] #93
- [x] #92

## Functional requirements

- The packages can be assembled locally (using bash).
- The packages can be assembled locally (using Act).
- The packages can be assembled automatically using GH Actions.

**Comment by AlexRuiz7** [comment]
## RPM

Required tools:

- rpm2cpio
- cpio
- rpm

1. Extract `wazuh-indexer-*.rpm` package using `rpm2cpio` to any directory.
2. Copy `wazuh-indexer.spec.rpm` to the same directory.
3. Run `rpmbuild`. See example below.

Issues:
- `_sharedstatedir` is by default set to `/usr/com`. Fixed with `%define _sharedstatedir /var/lib`
- `File not found: /app/rpm/BUILDROOT/wazuh-indexer-4.9.0-1.x86_64/usr/lib/systemd/system/opensearch-performance-analyzer.service`. File is missing, hosted in [opensearch-build](https://github.com/opensearch-project/opensearch-build/blob/a6fd12cc398cd571f008ddd52f92e3c111b4e9d9/scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch-performance-analyzer.service) repo. Fixed by copying over the file, and placing it into the correct location.

```console
rpmbuild --bb \
  --define "_topdir /app/rpm" \
  --define "_version 4.9.0" \
  --define "_architecture x86_64" \
  /app/rpm/opensearch.rpm.spec
```

**Comment by AlexRuiz7** [comment]
On hold due to https://github.com/wazuh/wazuh-packages/issues/2697

I'll be testing the new package for wazuh-indexer.

**Comment by AlexRuiz7** [comment]
#85 has been merged, but the work continues:

- [ ] Assemble DEB packages. The assembly of DEB packages failed, and we need to investigate why.
- [ ] Use [short SHA](https://stackoverflow.com/a/59819441/13918537) as commit reference to avoid huge package names.
- [ ] Implement correct architecture naming convention. Currently, x64 or arm64 is used, but these are dependent on the distribution. For example, RPM uses x86_64 and DEB uses amd64.

**Comment by AlexRuiz7** [comment]
#85 has been merged, but the work continues:

- [ ] Assemble DEB packages. The assembly of DEB packages failed, and we need to investigate why.
- [ ] Use [short SHA](https://stackoverflow.com/a/59819441/13918537) as commit reference to avoid huge package names.
- [ ] Implement correct architecture naming convention. Currently, x64 or arm64 is used, but these are dependent on the distribution. For example, RPM uses x86_64 and DEB uses amd64.
- [ ] Do not maintain configuration files of the security plugin, extend them from upstream.

**Comment by AlexRuiz7** [comment]
Issue closed partially. All problems found have been transformed into issues.

The generation of `wazuh-indexer` packages using GitHub workflows as been **completed but for** the **ARM64** architecture, as we need custom runners to build them.

- https://github.com/wazuh/wazuh-indexer/issues/111
